
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS problem CASCADE;
DROP TABLE IF EXISTS solution CASCADE;
DROP TABLE IF EXISTS video CASCADE;
DROP TABLE IF EXISTS submission CASCADE;